WebApplication1/Controllers/MenuController.cs
using Models.Fund;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class MenuController : Controller
    {
        private FundContext db = new FundContext();

        // 產生右側選單
        public ActionResult SidebarMenu()
        {
            var result = from m in db.Menu
                         join p in db.Menu on m.parentMenuId equals p.menuId into ps
                         from p in ps.DefaultIfEmpty()
                         select new MenuViewModel
                         {
                             firstOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? p.parentMenu.menuOrder : p.menuOrder) : m.menuOrder,
                             secondOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? p.menuOrder : m.menuOrder) : 0,
                             thirdOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? m.menuOrder : 0) : 0,
                             Menu = m
                         } into s
                         orderby s.firstOrder, s.secondOrder, s.thirdOrder
                         select s;

            foreach (var item in result) {
                Debug.WriteLine("First: " + item.firstOrder + " Second: " + item.secondOrder + " Third: " + item.thirdOrder + " name: " + item.Menu.menuName);
            }

            return PartialView("_SidebarMenu", result);
        }

        public ActionResult SidebarMenu2()
        {
            //產生選單測試區塊
            var menus = from m in db.MenuItem
                        select new MenuItemModel
                        {
                            menuItem = m
                        } into mi
                        orderby mi.menuItem.leftIndex
                        select mi;
            List<MenuItemModel> menuItems = menus.ToList();
            MenuItemModel poppedMenu = null;
            Stack<MenuItemModel> stackMenus = new Stack<MenuItemModel>();
            int level = 0;
            int preLeftIndex = 1;

            int totalCount = menuItems.Count();
            for (int i = 0; i < totalCount; i++) {
                MenuItemModel menuItem = menuItems.ElementAt(i);

                if (menuItem.menuItem.leftIndex == 1) {
                    //root
                    stackMenus.Push(menuItem);
                } else {
                    bool isEndNode = menuItem.IsEndNode();
                    int leftIndex = menuItem.menuItem.leftIndex;
                    int leftIndexRange = leftIndex - preLeftIndex;
                    preLeftIndex = leftIndex;

                    switch (leftIndexRange) {
                        case 1:
                            //this is subNode of pre (to next level)
                            level++;
                            if (!isEndNode) {
                                stackMenus.Push(menuItem);
                            } else {
                                if (stackMenus.Any()) {
                                    poppedMenu = stackMenus.Pop();
                                    poppedMenu.DropDownMenus.Add(menuItem);
                                }
                            }
                            break;
                        case 2:
                            //this is sibNode of pre (same level)
                            if (!isEndNode) {
                                stackMenus.Push(poppedMenu);
                                stackMenus.Push(menuItem);
                            } else {
                                poppedMenu.DropDownMenus.Add(menuItem);
                            }
                            break;
                        default:
                            //this is upper n-2 level sibNode of pre (to upper n-2 level)
                            int shiftLevel = leftIndexRange - 2;
                            level = level - shiftLevel;

                            for (int j = 0; j < shiftLevel; j++) {
                                MenuItemModel tempPoppedMenu = stackMenus.Pop();
                                tempPoppedMenu.DropDownMenus.Add(poppedMenu);
                                poppedMenu = tempPoppedMenu;
                            }

                            if (!isEndNode) {
                                stackMenus.Push(poppedMenu);
                                stackMenus.Push(menuItem);
                            } else {
                                poppedMenu.DropDownMenus.Add(menuItem);
                            }
                            break;
                    }
                    menuItem.Level = level;
                }

                //Last one
                if ((i + 1) == totalCount) {
                    while (stackMenus.Any()) {
                        MenuItemModel tempPoppedMenu = stackMenus.Pop();
                        if (poppedMenu != null) {
                            tempPoppedMenu.DropDownMenus.Add(poppedMenu);
                        }
                        poppedMenu = tempPoppedMenu;
                    }
                }
            }

            return PartialView("_SidebarMenu", poppedMenu);
        }

        // GET: Menu
        public ActionResult Index()
        {
            var result = from m in db.Menu
                         join p in db.Menu on m.parentMenuId equals p.menuId into ps
                         from p in ps.DefaultIfEmpty()
                         select new MenuViewModel
                         {
                             firstOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? p.parentMenu.menuOrder : p.menuOrder) : m.menuOrder,
                             secondOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? p.menuOrder : m.menuOrder) : 0,
                             thirdOrder = m.parentMenuId.HasValue ? (p.parentMenuId.HasValue ? m.menuOrder : 0) : 0,
                             Menu = m
                         } into s
                         orderby s.firstOrder, s.secondOrder, s.thirdOrder
                         select s.Menu;
            return View(result);
        }

        // GET: Menu/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null) {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menu/Create
        public ActionResult Create()
        {
            Assembly asm = Assembly.GetAssembly(typeof(MvcApplication));

            var controlleractionlist = asm.GetTypes()
                    .Where(type => typeof(System.Web.Mvc.Controller).IsAssignableFrom(type))
                    .SelectMany(type => type.GetMethods(BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public))
                    .Where(m => !m.GetCustomAttributes(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), true).Any())
                    .Select(x => new { Controller = x.DeclaringType.Name, Action = x.Name, ReturnType = x.ReturnType.Name, Attributes = String.Join(",", x.GetCustomAttributes().Select(a => a.GetType().Name.Replace("Attribute", ""))) })
                    .OrderBy(x => x.Controller).ThenBy(x => x.Action).ToList();

            foreach (var item in controlleractionlist) {
                Debug.WriteLine("Controller: " + item.Controller + " Action: " + item.Action + " ReturnType: " + item.ReturnType + " Attributes: " + item.Attributes);
            }
            return View();
        }

        // POST: Menu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "menuId,actionName,controllerName,menuName,menuLevel,menuOrder,iconName")] Menu menu)
        {
            if (ModelState.IsValid) {
                menu.menuId = Guid.NewGuid();
                db.Menu.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(menu);
        }

        // GET: Menu/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null) {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "menuId,actionName,controllerName,menuName,menuLevel,menuOrder,iconName")] Menu menu)
        {
            if (ModelState.IsValid) {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(menu);
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menu.Find(id);
            if (menu == null) {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

WebApplication1/Controllers/ST001Controller.cs
using Models.Fund;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ST001Controller : Controller
    {
        private FundContext db = new FundContext();

        public ActionResult Test() {
            return View();
        }

        // GET: ST001
        public ActionResult Index()
        {
            return View(db.ST001.ToList());
        }

        // GET: ST001/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ST001 sT001 = db.ST001.Find(id);
            if (sT001 == null) {
                return HttpNotFound();
            }
            return View(sT001);
        }

        // GET: ST001/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ST001/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "stId,stCode,stName")] ST001 sT001)
        {
            if (ModelState.IsValid) {
                DateTime currentTime = DateTime.Now;
                sT001.stId = Guid.NewGuid();
                sT001.CreateDateTime = currentTime;
                sT001.LastModifyTime = currentTime;
                db.ST001.Add(sT001);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sT001);
        }

        // GET: ST001/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ST001 sT001 = db.ST001.Find(id);
            if (sT001 == null) {
                return HttpNotFound();
            }
            return View(sT001);
        }

        // POST: ST001/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "stId,stCode,stName,CreateDateTime")] ST001 sT001)
        {
            if (ModelState.IsValid) {
                sT001.LastModifyTime = DateTime.Now;
                db.Entry(sT001).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sT001);
        }

        // GET: ST001/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ST001 sT001 = db.ST001.Find(id);
            if (sT001 == null) {
                return HttpNotFound();
            }
            return View(sT001);
        }

        // POST: ST001/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ST001 sT001 = db.ST001.Find(id);
            db.ST001.Remove(sT001);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Search(string searchString)
        {
            var sT001s = from m in db.ST001 select m;
            if (!String.IsNullOrEmpty(searchString)) {
                sT001s = sT001s.Where(s => s.stCode.Contains(searchString));
            }
            return View("Index", sT001s);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-reboot.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-grid.css" rel="stylesheet" type="text/css" />

    <!-- Custom CSS -->
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css" integrity="sha384-QokYePQSOwpBDuhlHOsX0ymF6R/vLk/UQVz3WHa6wygxI5oGTmDTv8wahFOSspdm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/fontawesome.css" integrity="sha384-vd1e11sR28tEK9YANUtpIOdjGW14pS87bUBuOIoBILVWLFnS+MCX9T6MMf0VdPGq" crossorigin="anonymous">

</head>
<body>
    <div class="wrapper">

        <!-- Sidebar -->
        @{Html.RenderAction("SidebarMenu", "Menu");}

        <!-- Page Content-->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="navbar-btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
            </nav>
            <div class="body-content">
                @RenderBody()
            </div>
        </div>

    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/Sortable.js"></script>
    <@*<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>*@>
    <script src="~/Scripts/feather.js"></script>
    <script>
        $(document).ready(function () {

            //產生feather icon用
            feather.replace();

            /*$("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });*/

            //選單收合按鈕
            $('#sidebarCollapse').on('click', function () {
                $(this).toggleClass('active');
                // open or close navbar
                $('#sidebar, #content').toggleClass('active');
                // close dropdowns
                $('a[aria-expanded=true]').click();
            });
        });
    </script>
    @RenderSection("Script", required: false);
</body>
</html>

WebApplication1/Views/Shared/_SidebarMenu.cshtml
@using Models.Fund;
@model IEnumerable<WebApplication1.Models.MenuViewModel>

<nav id="sidebar">
    <div class="sidebar-header">
        <h3>Bootstrap Sidebar</h3>
    </div>

    <ul id="sidebarList" class="list-unstyled">
        @Html.SidebarMenuActionLink("Dashboard", "Index", "Home", "bar-chart-2")
        <li class="sidebar-heading">
            <span>Dummy Heading</span>
        </li>
        <li class="sidebar-menu">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" level="2">
                <span>
                    <i class="fas fa-home"></i>
                </span>
                Home
            </a>
            <ul id="homeSubmenu" class="collapse list-unstyled" data-parent="#sidebar">
                <li><a href="#">Home 1</a></li>
                <li><a href="#">Home 2</a></li>
                <li><a href="#">Home 3</a></li>
            </ul>
        </li>
        <li class="sidebar-menu">
            <a href="#">
                <span>
                    <i class="fas fa-briefcase"></i>
                </span>
                About
            </a>
        </li>
        <li class="sidebar-menu">
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" level="2">
                <span>
                    <i class="fas fa-copy"></i>
                </span>
                Pages
            </a>
            <ul id="pageSubmenu" class="collapse list-unstyled" data-parent="#sidebar">
                <li>
                    <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Page 1</a>
                    <ul id="pageSubmenu1" class="collapse list-unstyled" data-parent="#pageSubmenu">
                        <li><a href="#">P 1</a></li>
                        <li><a href="#">P 2</a></li>
                    </ul>
                </li>
                <li><a href="#">Page 2</a></li>
                <li><a href="#">Page 3</a></li>
            </ul>
        </li>
        <li class="sidebar-menu">
            <a href="#">
                <span>
                    <i class="fas fa-user-edit"></i>
                </span>
                Portfolio
            </a>
        </li>
        <li class="sidebar-menu">
            <a href="#">
                <span>
                    <i class="fas fa-paper-plane"></i>
                </span>
                Contact
            </a>
        </li>
        @Html.SidebarHeading("Menu")
        @Html.SidebarMenuActionLink("Menu", "Index", "Menu", "sidebar")
        @Html.SidebarHeading("Setting")
        @Html.SidebarMenuActionLink("Setting", "Index", "ST001", "fas fa-cog")

        @*@foreach (var group in Model.GroupBy(m => m.firstOrder)) {
            foreach (var subGroup in group.GroupBy(m => m.secondOrder)) {
                @Html.SidebarMenuActionLink(subGroup);
            }
        }*@
        @*@Html.GenerateMenu(Model);*@
        @*@Html.GenerateMenu(Model.First());*@
    </ul>
</nav>